feat: 그리드 push 구현
Team-Snacks/frontend pull request #3
Opened 2022-11-25 07:55 UTC by jyhyun97

#### 연결된 이슈
[노션](https://usanglee.notion.site/8704f26742274248810e52f2d7fbecea)
## Pull Request 설명
![화면-기록-2022-11-25-오후-4 46 46](https://user-images.githubusercontent.com/72776427/203928585-15bb5ecc-06fe-4053-93d0-5a485952c696.gif)

- 위 gif와 같이 위젯들을 밀어낼 수 있는 동작이 추가되었습니다
- 이동 불가 판정인데도 이동이 되는 버그가 있으나, 기간 상 추후 fix하고 다음주부턴 다른 컴포넌트 작업하는 것이 나을 것으로 판단. 우선 겹치거나 그리드 바깥으로 나가는 등 큰 버그만 픽스하였습니다

2022-11-25 08:43 UTC, scarf005 requested changes
수고 많으셨습니다. 스타일, 가변성 관련해서는 추후에 eslint를 적용하면 될 것 같습니다. 함수명 관련해서만 확인해주시겠어요?

2022-11-25 08:43 UTC, scarf005 commented on frontend/src/components/users/Grid.tsx
> +    if (isPushable(widgets[index], cursorPosition, widgets) !== false) {
```suggestion
    if (isPushable(widgets[index], cursorPosition, widgets)) {
```
`!== false` 는 `=== true` 란 뜻인데 더 넣을 필요는 없을 것 같습니다.

2022-11-25 08:43 UTC, scarf005 commented on frontend/src/components/users/Grid.tsx
> +      widgets[index].pos = widgets[index].pos.add(cursorPosition)
widgets를 직접 수정해야 해서 (순수 함수가 아니어서) 나중에 테스트하기 어려워질것 같다는 생각이 듭니다.
widgets를 atom을 이용해 글로벌 변수로 만들고 추후에 `setWidgets`를 사용하는 것이 좋겠습니다.

2022-11-25 08:43 UTC, scarf005 commented on frontend/src/components/users/GridTools.ts
> +  return movableToEmpty(widget, cursorPosition, tryPushWidgets) !== false
```suggestion
  return movableToEmpty(widget, cursorPosition, tryPushWidgets)
```

2022-11-25 08:43 UTC, scarf005 commented on frontend/src/components/users/GridTools.ts
> +  })
boolean 함수인데 부작용이 있습니다. `push` 등의 함수로 따로 빼는 것이 나을 것 같습니다.

2022-11-25 08:43 UTC, scarf005 commented on frontend/src/components/users/GridTools.ts
> +const tryPush = (widget: WidgetType, direction: Vec2, widgets: Widgets) => {
```suggestion
const isPushableTo = (widget: WidgetType, direction: Vec2, widgets: Widgets) => {
```
특정 방향으로 옮길 수 있는지 여부를 확인하고, bool 값을 반환하므로 (`is ~`), `isPushableTo` 같은 이름이 좋을 것 같습니다.

2022-11-25 08:43 UTC, scarf005 commented on frontend/src/components/users/GridTools.ts
> +  //4. 나머지 경우는 false
```suggestion
/**
 * widget를 vec2 방향으로 이동할 수 있는지 확인하기 
 *
 * 1. coordinateRangeWidgets로 옮길 곳에 어떤 위젯들이 차지하고 있는 지 확인하고
 * 2. 만약 그 리스트가 비어있으면 빈 배열이라는 거니까 true
 * 3. 만약 그 리스트에 widget만 있으면 어차피 자기 자신이니 true
 * 4. 나머지 경우는 false
 */
const tryPush = (widget: WidgetType, direction: Vec2, widgets: Widgets) => {
```
에디터에서 함수명을 호버링 시 주석을 볼 수 있도록 [tsdoc 형식](https://tsdoc.org)을 따르는 것이 좋을 것 같습니다.

2022-11-28 02:55 UTC, scarf005 approved these changes
확인했습니다. 수고 많으셨어요!

2022-11-28 02:56 UTC, jyhyun97 commented on frontend/src/components/users/Grid.tsx
> +    if (isPushable(widgets[index], cursorPosition, widgets) !== false) {
반영했습니다!

2022-11-28 02:58 UTC, jyhyun97 commented on frontend/src/components/users/Grid.tsx
> +      widgets[index].pos = widgets[index].pos.add(cursorPosition)
지금은 시간이 좀 걸릴 것 같아서 일단 두었는데 나중에 movableToEmpty, moveItemSwap까지 전부 한번에 리팩토링 하겠습니다
변경된 객체 배열을 반환하는 식으로 만들고, Grid에서 setWidgets를 사용해 변경하는 느낌으로요

2022-11-28 02:58 UTC, jyhyun97 commented on frontend/src/components/users/GridTools.ts
> +  return movableToEmpty(widget, cursorPosition, tryPushWidgets) !== false
반영했습니다

2022-11-28 03:02 UTC, jyhyun97 commented on frontend/src/components/users/GridTools.ts
> +  })
일단 이 부분은 아직 수정 안했습니다  부작용이 어떤 건지 좀 더 자세하게 설명해주시면 좋겠습니다

2022-11-28 03:02 UTC, jyhyun97 commented on frontend/src/components/users/GridTools.ts
> +const tryPush = (widget: WidgetType, direction: Vec2, widgets: Widgets) => {
반영했습니다

2022-11-28 03:02 UTC, jyhyun97 commented on frontend/src/components/users/GridTools.ts
> +  //4. 나머지 경우는 false
반영했습니다 이왕 하는 김에 다른 함수들에도 추가했습니다~~

2022-11-28 03:03 UTC, jyhyun97 commented
수정 커밋 및 코멘트 올렸습니다! 일단 머지하겠습니다~!

2022-11-28 03:04 UTC, merged